config/routes.rb
Rails.application.routes.draw do
  resources :ripples, :except => [:edit, :destroy, :update] do
    collection do
      match 'next', :via => [:get]
      match 'prev', :via => [:get]
      match 'oldest', :via => [:get]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ripple.rb
class Ripple < ApplicationRecord
  validates :name, :message, presence: true
  validates :url, allow_blank: true, format: { with: URI::regexp(%w(http https)), message: "URL must begin with http:// or https://" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show]
  PER_PAGE = 10

  # GET /ripples
  # GET /ripples.json
  def index
    session[:page] = 0
    @ripples = Ripple.all.order("created_at DESC").limit(PER_PAGE).offset(session[:page] * PER_PAGE)
    @total = Ripple.count / PER_PAGE
    if(0..@total).include?(@page.to_i) == FALSE
      redirect_to ripples_path
    end
  end

  # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  # GET /ripples/1/edit
#  def edit
#  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)

    respond_to do |format|
      if @ripple.save
        format.html { redirect_to ripples_path, notice: 'Ripple was successfully created.' }
        format.json { render :show, status: :created, location: @ripple }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end
    end
  end

  def next
    if session[:page] != Ripple.count / PER_PAGE
      session[:page] += 1
      @ripples = Ripple.all.order("created_at DESC").limit(PER_PAGE).offset(session[:page] * PER_PAGE)
      render 'ripples/index'
    else
      redirect_to ripples_path
    end
  end

  def prev
    if session[:page] != 0
      session[:page] -= 1
      @ripples = Ripple.all.order("created_at DESC").limit(PER_PAGE).offset(session[:page] * PER_PAGE)
      render 'ripples/index'
    else
      redirect_to ripples_path
    end
  end

  def oldest
    session[:page] = Ripple.count / PER_PAGE
      @ripples = Ripple.all.order("created_at DESC").limit(PER_PAGE).offset(session[:page] * PER_PAGE)
      render 'ripples/index'
  end

  # PATCH/PUT /ripples/1
  # PATCH/PUT /ripples/1.json
#  def update
#    respond_to do |format|
#      if @ripple.update(ripple_params)
#        format.html { redirect_to @ripple, notice: 'Ripple was successfully updated.' }
#        format.json { render :show, status: :ok, location: @ripple }
#      else
#        format.html { render :edit }
#        format.json { render json: @ripple.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /ripples/1
  # DELETE /ripples/1.json
#  def destroy
#    @ripple.destroy
#    respond_to do |format|
#      format.html { redirect_to ripples_url, notice: 'Ripple was successfully destroyed.' }
#      format.json { head :no_content }
#    end
#  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:name, :url, :message)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Consciousmess</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <br>
  </head>
  <div id="header">
    <br>
    <h1 class="title">CONSCIOUS/mess</h1>
    <h2 class="title">...a stream of anonymous online ramblings</h2>
  </div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/ripples/_form.html.erb
<%= form_for(ripple) do |f| %>
  <% if ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ripple.errors.count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>State What's On Your Mind</h1>

  <div class="field">
    <%= f.label "Your name or alias (required)" %>
    <%= f.text_field :name, :size => 50 %>
  </div>

  <div class="field">
    <%= f.label "A website, yours or otherwise (optional)" %>
    <%= f.text_field :url, :size => 50 %>
  </div>

  <div class="field">
    <%= f.label "Your message/note/quote/rant (required)" %>
    <%= f.text_area :message, rows: 20, cols:65 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ripples/edit.html.erb
<h1>Editing Ripple</h1>

<%= render 'form', ripple: @ripple %>

<%= link_to 'Show', @ripple %> |
<%= link_to 'Back', ripples_path %>

app/views/ripples/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ripples.each do |ripple| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <% if ripple.url.nil? or ripple.url == ""%>
        <td><%= ripple.name %></td>
      <% else %>
        <td><%= link_to ripple.name, ripple.url %></td>
      <% end  %>

        <td><%= truncate(ripple.message, length: 100) %></td>
        <td><%= ripple.created_at %></td>
        <td><%= link_to 'Show', ripple %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Newest', ripples_path %>
<%= link_to 'Previous 10 Ripples', prev_ripples_path %>
<%= link_to 'Next 10 Ripples', next_ripples_path %>
<%= link_to 'Oldest', oldest_ripples_path %> <br><br>
<%= link_to 'New Ripple', new_ripple_path %>

app/views/ripples/new.html.erb
<%= render 'form', ripple: @ripple %>

<%= link_to 'Back', ripples_path %>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>

  <strong>
    <% if @ripple.url.nil? %>
      <%= @ripple.name %> said:
    <% else %>
      <%= link_to @ripple.name, @ripple.url %> said:
    <% end %>
  </strong>




<p>
  <strong>Message:</strong>
  <%= @ripple.message %>
</p>

<%= link_to 'Back', ripples_path %>